@startuml
left to right direction

actor "Agricultural Manager" as AG #grey
actor "Product Owner" as PO #green

rectangle "Agricultural facility app"{
    usecase "USBD01 - I intend to create a dictionary of data/glossary." as UC1
    usecase "USBD02 - I intend to develop the relational model (logical level)." as UC2
    usecase "USBD03 - I want the relational model to be instantiated (physical level)." as UC3
    usecase "USBD04 - I want data to be imported from a legacy system, provided in a spreadsheet." as UC4
    usecase "USBD05 - I want to know the quantity of products harvested in a given portion, for each product, in a given time interval." as UC5
    usecase "USBD06 - I want to know the number of protection factors applied to a given portion, for each type of factor, in a given interval of time." as UC6
    usecase "USBD07 - I want to know the number of operations carried out in a given installment, for each type of operation, in a given time interval." as UC7
    usecase "USBD08 - I intend to know the production factor with more applications in the agricultural installation in a given time interval." as UC8
    usecase "USBD09 - I want to know the number of applications of each type of production factor applied in the agricultural installation in a given interval of time." as UC9
    usecase "USBD10 - I intend to know what is the parcel with more irrigation operations in a given time interval." as UC10
    usecase "USBD11 - I want to register a sowing operation." as UC11
    usecase "USBD12 - I want to register a weeding operation." as UC12
    usecase "USBD13 - I want to register a harvesting operation." as UC13
    usecase "USBD14 - I want to register a production factor application operation." as UC14
    usecase "USBD15 - I want to register a pruning operation." as UC15
    usecase "USBD16 - I intend to obtain the list of factors collected from a given plot, for each species, in a given time interval." as UC16
    usecase "USBD17 - I want to obtain a list of production factors applied to a given plot, and their respective quantities, for each type of component substance, in a given time interval." as UC17
    usecase "USBD18 - I want to obtain the list of operations carried out on a given plot, for each type of operation, in a given time interval." as UC18
    usecase "USBD19 - I intend to obtain the list of production factor applications applied in the agricultural installation, including the plot and crop (if applicable), by type of production factor, in a given time interval." as UC19
    usecase "USBD20 - I want to obtain the monthly irrigation totals for each plot, in a given time interval." as UC20
    usecase "USLP01 - I want to the domain model to be developed (conceptual level)." as UC21
    usecase "USLP02 - I want to define a functionality that consists of simulating an irrigation system controller." as UC22
    usecase "USLP03 - I intend to develop a functionality that allows the irrigation plan generated by the controller simulator developed at UC22 to be automatically compressed." as UC23
    usecase "USLP04 - I intend to develop functionalities that allow the evocation of UC11." as UC24
    usecase "USLP05 - I intend to develop functionalities that allow the evocation of UC12." as UC25
    usecase "USLP06 - I intend to develop functionalities that allow the evocation of UC13." as UC26
    usecase "USLP07 - I intend to develop functionalities that allow the evocation of UC14." as UC27
    usecase "USLP08 - I intend to develop functionalities that allow the evocation of UC15." as UC28
    usecase "USBD21 - I want the relational model to be updated (logical and physical level) in light of new requirements and user stories." as UC29
    usecase "USBD22 - I want updated data from a legacy system to be imported, provided in a spreadsheet." as UC30
    usecase "USBD23 - I want the dictionary to be updated data/glossary" as UC31

    PO -- UC1
    PO -- UC2
    PO -- UC3
    PO -- UC4
    PO -- UC21
    PO -- UC22
    PO -- UC23
    PO -- UC24
    PO -- UC25
    PO -- UC26
    PO -- UC27
    PO -- UC28
    AG -- UC5
    AG -- UC6
    AG -- UC7
    AG -- UC8
    AG -- UC9
    AG -- UC10
    AG -- UC11
    AG -- UC12
    AG -- UC13
    AG -- UC14
    AG -- UC15
    AG -- UC16
    AG -- UC17
    AG -- UC18
    AG -- UC19
    AG -- UC20
    AG -- UC21
    PO -- UC29
    PO -- UC30
    PO -- UC31


}
@enduml