SELECT
    AP.PARCELDESIGNATION,
    OP.commonName,
    P.startDate AS START_DATE,
    P.endDate AS END_DATE,
    SUM(P.quantity) AS QUANTITY_OF_PRODUCTS

FROM AGRICULTURALPARCEL AP
         INNER JOIN PLANTATION P ON AP.ParcelID = P.AGRICULTURALPARCELPARCELID
         INNER JOIN CROP O ON P.cycleID = O.cropID
         INNER JOIN SPECIES OP ON O.cropID = OP.speciesID

WHERE
    P.startDate BETWEEN TO_DATE('2015-01-07', 'YYYY-MM-DD') AND TO_DATE('2030-07-31', 'YYYY-MM-DD')

GROUP BY
    AP.PARCELDESIGNATION,
    OP.commonName,
    P.startDate,
    P.endDate
ORDER BY
    QUANTITY_OF_PRODUCTS DESC;

